version: '2.1'
services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.7.0
    container_name: elasticsearch
    environment:
      - node.name=snowstorm
      - cluster.name=snowstorm-cluster
      - cluster.initial_master_nodes=snowstorm
      - "ES_JAVA_OPTS=-Xms12g -Xmx12g"
    volumes:
      - /data/elastic:/usr/share/elasticsearch/data
    networks:
      elastic:
        aliases:
         - es
    healthcheck:
      test: ["CMD", "curl", "-f", "http://es:9200"]
      interval: 1s
      timeout: 1s
      retries: 60
    ports:
      - 127.0.0.1:9200:9200
    mem_reservation: 12g


  snowstorm:
    image: snomedinternational/snowstorm:latest
    container_name: snowstorm
    restart: always
    depends_on:
      elasticsearch:
        condition: service_healthy
    entrypoint: java -Xms6g -Xmx12g -jar snowstorm.jar --delete-indices --import=/snomed.zip --elasticsearch.urls=http://es:9200
   #entrypoint: java -Xms2g -Xmx8g -jar snowstorm.jar --elasticsearch.urls=http://es:9200
    networks:
      elastic:
        aliases:
         - snowstorm
    ports:
      - 8080:8080
    volumes:
      - /data/snomed.zip:/snomed.zip

#  browser:
#    image: snomedinternational/snomedct-browser:latest
#    container_name: browser
#    depends_on:
#      - snowstorm
#    links:
#      - snowstorm:snowstorm
#    networks:
#      - elastic
#    environment:
#      - API_HOST=http://snowstorm:8080/
#    ports:
#      - 80:80
#    restart: always


networks:
  elastic:

